### ISSUE TITLE
Was late-chunking used for jina-embeddings-v3 submission on MTEB?

### ISSUE THREAD

**Issue by dantetemplar** [jina-ai/late-chunking#23]
I see jina-embeddings-v3 got high score on MTEB, was late-chunking used?

https://huggingface.co/spaces/mteb/leaderboard
https://huggingface.co/jinaai/jina-embeddings-v3

**Comment by guenthermi** [comment]
No, for reporting the MTEB score, no kind of chunking was used (It might not be considered a fair comparison). Nevertheless, I think for many retrieval task you can get even higher scores if you use some chunking + late chunking. We actually wrote a blog post about when chunking and late chunking is better for retrieval: https://jina.ai/news/still-need-chunking-when-long-context-models-can-do-it-all/

**Comment by guenthermi** [comment]
If you want to reproduce the scores on the MTEB leaderboard you have to make sure to to use the right task attribute for each task. Also not all retrieval task using the same task attributes, because, some are symmetric (they use text-matching) and some are asymmetric (they use the query and passage task attributes). I am not sure if it is detailed in the README, but it is definitely in our paper: https://arxiv.org/abs/2409.10173

**Comment by dantetemplar** [comment]
Thanks!
